- name: conditional
  hosts: all
  connection: network_cli
  gather_facts: False

  tasks:
  
  - name: gather_ios_facts
    cisco.ios.ios_facts:
      gather_subset: all
    register: facts

  - name: debug
    debug: 
      msg: "{{item}}"
    loop: "{{facts.ansible_facts.ansible_net_interfaces | dict2items}}"
    when: item.key=="Ethernet0/1"
    tags: ["one"]

  - name : show
    debug:
      msg: "{{facts}}"
    tags: ["two"]
  