
l3_interfaces:
 
  - name: gig 3
    ipv4: 192.0.2.5/31
    description: "Wan link to ISP (underlay), made by ansible :)"
    vrf: underlay

  - name: gig 2
    ipv4: 192.168.1.13/30
    description: "DownLink to Collapsed Core D2.EITAN.COM, made by ansible :)" 
    vrf: site_2

  - name: gig 1
    ipv4: 192.168.1.1/30
    description: "DownLink to Collapsed Core D1.EITAN.COM, made by ansible :)" 
    vrf: site_2

##### loopbacks

  - name: loopback1
    ipv4: 1.1.1.1/32
    description: "Loopback for Tunnel Source - Underlay VRF, made by ansible :)"
    vrf: underlay

  - name: loopback2
    ipv4: 10.10.10.10/32
    description: "BGP Overlay Loopback Update-Source, made by ansible :)"
    vrf: site_2




################################################ OSPF VARS


ospf_ipv4: 
  - process_id: 1
    vrf: site_2
    router_id: 1.1.1.0
    areas:
      - name: 0
        authentication: true
        networks:
            
          - ip: 192.168.1.0
            wildcard: 0.0.0.3
            
          - ip: 192.168.1.12
            wildcard: 0.0.0.3
        default_originate: 
          metric: 30
        p2p_interfaces:
         
          - name: GigabitEthernet1
          - name: GigabitEthernet2
           
           

  - process_id: 2
    vrf: site_2
    areas:
      - name: 0
        authentication: false
        networks:
          - ip: 10.0.0.0
            wildcard: 0.0.0.255
            
          - ip: 10.10.10.10
            wildcard: 0.0.0.0
          
##############################################################################









tunnel_interfaces:
    ipaddr: "10.0.0.1"


crypto_private:
  ikev2:
    keyring:
      peers:
        - name: R4
          address: 4.4.4.4  
          pre_shared_key: mySecret14
        - name: R2
          address: 2.2.2.2 
          pre_shared_key: mySecret12
        - name: R6
          address: 6.6.6.6 
          pre_shared_key: mySecret16
    profile:
      local_identity: "1.1.1.1 " 
      match_identities:
        - address: 2.2.2.2 255.255.255.255
        - address: 6.6.6.6 255.255.255.255
        - address: 4.4.4.4 255.255.255.255
  


tunnel_vars:
  - tunnel: "tunnel 1"
    ip_address: 10.0.0.1/24
    vrf: "site_2"
    phase_3_action: "shortcut"
    hub_tunnel_ip: "10.0.0.4"
    hub_NBMA_ip: "4.4.4.4"




bgp:
  asn: "64540"
  router_id: 1.1.1.1
  vrf:
    - name: site_2
      redistribute: "ospf 1"
      neighbors:
        - ip: 40.40.40.40
          remote_as: "65510"
          ebgp_multihop: "3"
          source: Loopback2
          activate: true
    # - name: underlay
    #   networks:
    #     - "1.1.1.1 mask 255.255.255.255"
    #     - "192.0.2.4 mask 255.255.255.254"
    #   neighbors:
    #     - ip: 192.0.2.4
    #       remote_as: "200"
    #       local_as: "100 no-prepend replace-as"
    #       allowas: true
    #       activate: true


         

qos_private:
  wan_interface: GigabitEthernet3
  lan_interfaces:
    - GigabitEthernet1
    - GigabitEthernet2


nat:
  nat_range:
  - "10.0.0.0/27"
  - "192.168.1.0/27"
  nat_vrf: site_2
          



SSH_MGMT:
  Station: 200.0.0.0
  lines: 0 530
  vrf: underlay



     


 


   