- name: removing configuration...
  hosts: Switches
  gather_facts: False
  tasks:
  - name: erase policy-maps before provisioning  :)))))
    cisco.ios.ios_config:
      lines:

        - no policy-map {{item}}
    loop: "{{policy_maps}}"  
    register: commands1
    when: "'Edges' in group_names"

    
  - name: erase class-maps before provisioning   :)))))
    cisco.ios.ios_config:
      lines:

        - no class-map {{item}}
    loop: "{{class_maps}}"
    register: commands2
    when: "'Edges' in group_names"

        

  - name: erase ACLS before provisioning  :)))))
    cisco.ios.ios_config:
      lines:

        - no ip access-list extended {{item}}
        - no ip access-list standard {{item}}

    loop: "{{extended_acls}}"
    register: commands3
    when: "'Edges' in group_names"



  - name: erase ospf before provisioning   :)))))
    cisco.ios.ios_config:
      lines:

        - no router ospf {{item}}
        
    loop: "{{ospf_processes}}"
    tags: [one]
    when: "'Edges' in group_names"
  


  - name: erase DMVPN+ipsec tunnel configuration :)))))
    cisco.ios.ios_config:
      lines:
        - interface tunnel 1
        - exit
        - default interface tunnel 1
    when: "'Edges' in group_names"

  - name: erase leaking route-map on hub  :)))))
    cisco.ios.ios_config:
      lines:
        - no route-map FILTER_INTERNET_FROM_SPOKES
    when: inventory_hostname == "R4.EITAN.COM"
  - name: erase leaking route-map on hub  :)))))
    cisco.ios.ios_config:
      lines:
        - no route-map FILTER_INTERNET_FROM_HUB
    when: 
      - inventory_hostname != "R4.EITAN.COM"
      - "'Edges' in group_names"
        
  

  - name: erase ipsec  & IKEv2 before provisioning  :)))))
    cisco.ios.ios_config:
      lines:
        - crypto ipsec profile IKEV2_IPSEC_PROFILE
        - crypto ikev2 policy IKEV2_POLICY
        - crypto ikev2 profile IKEV2_PROFILE
        - crypto ikev2 keyring IKEV2_KEYRING 
        - crypto ipsec transform-set IKEV2_TRANSFORM_SET esp-aes 256 esp-sha256-hmac
        - crypto ikev2 proposal IKEV2_PROPOSAL 
        - no crypto ipsec profile IKEV2_IPSEC_PROFILE
        - no crypto ikev2 policy IKEV2_POLICY
        - no crypto ikev2 profile IKEV2_PROFILE
        - no crypto ikev2 keyring IKEV2_KEYRING 
        - no crypto ipsec transform-set IKEV2_TRANSFORM_SET esp-aes 256 esp-sha256-hmac
        - no crypto ikev2 proposal IKEV2_PROPOSAL 
    when: "'Edges' in group_names"
        

  - name: erase overlay BGP before provisioning   :)))))
    cisco.ios.ios_config:
      lines:

        - no address-family ipv4 vrf {{ bgp['vrf'][0]['name'] }}
      parents: 
        - router bgp {{ bgp.asn }}
  
  - name: erase PAT interfaces commands before provisioning   :)))))
    cisco.ios.ios_config:
      lines:

        - no ip nat inside
      parents: 
        - interface {{qos_private.lan_interfaces[0]}}
        - interface {{qos_private.lan_interfaces[1]}}
    when: 
    - "'Edges' in group_names"
    - "'hub' not in group_names"
    tags: [three]

  
  - name: erase PAT interfaces commands before provisioning   :)))))
    cisco.ios.ios_config:
      lines:

        - no ip nat outside
      parents: 
        - interface {{qos_private.wan_interface}}
    when: 
      - "'hub' not in group_names"
      - "'Edges' in group_names"
  
  - name: erase PAT interfaces commands before provisioning   :)))))
    cisco.ios.ios_config:
      lines:

        - ip nat inside source list NAT-IN-LOCAL interface {{qos_private.wan_interface}} vrf {{nat.nat_vrf}} overload
        - no ip nat inside source list NAT-IN-LOCAL interface {{qos_private.wan_interface}} vrf {{nat.nat_vrf}} overload
    when: 
      - "'hub' not in group_names"
      - "'Edges' in group_names"
      
  - name: erase Edges VTY-line configuration before provisioning   :)))))
    cisco.ios.ios_config:
      lines:
        - no ip access-list standard SSH_MGMT
        - line vty {{SSH_MGMT.lines}} 
        - no access-class SSH_MGMT in vrfname {{SSH_MGMT.vrf}}
    when: "'Edges' in group_names and inventory_hostname != 'R4.EITAN.COM'"

  - name: erase Edges NAT-IN-LOCAL ACL before provisioning   :)))))
    cisco.ios.ios_config:
      lines:
        - no ip access-list standard NAT-IN-LOCAL
    when: 
      - "'hub' not in group_names"
      - "'Edges' in group_names"

  - name: erase Lan interface configuration on Spokes  :)))))
    cisco.ios.ios_config:
      lines:
        - default interface {{qos_private.lan_interfaces[0]}}
        - default interface {{qos_private.lan_interfaces[1]}}
    when: 
      - "'Edges' in group_names"
      - "'hub' not in group_names"
    tags: [four]
   
  - name: erase loopbacks on spokes  :)))))
    cisco.ios.ios_config:
      lines:
        - interface loopback 0
        - interface loopback 1
        - interface loopback 2
        - no interface loopback 0
        - no interface loopback 1
        - no interface loopback 2
    when: 
      - "'Edges' in group_names"
      - "'hub' not in group_names"
    tags: [five] 

  - name: erase Loopbacks on hub  :)))))
    cisco.ios.ios_config:
      lines:
        - interface loopback 1
        - interface loopback 2
        - no interface loopback 1
        - no interface loopback 2
    when: inventory_hostname == "R4.EITAN.COM"
    tags: [six]


  - name: erase Banner :)))))
    cisco.ios.ios_config:
      lines:
        - no banner motd
